### ISSUE TITLE
Definition of algebra

### ISSUE THREAD

**Issue by davidfarmer** [remkes/linearalgebra#3]
In Definition 1.2.1. "algebra" is defined as the study of sets with structure.

That is true, but possibly too expansive since it includes topology and maybe also analysis.

I suggest something like "the study of sets where the elements act as operations".  And then "structure" could be replaced by "operation" in
the remainder of the definition.

Just a suggestion: it is your book, of course!  (And I don't think my
wording is optimal.  Maybe "transformation" is better than "operation"?)

**Comment by remkes** [comment]
It is a bit too expansive, I agree. I think when I originally wrote this, I stared with the something like "algebra is the study of sets with algebraic structure", which is about as useless as possible to give to first-years. I'll think about rephrasing it, but I might keep it overly simply and a bit too broad for the pedagogical value of presenting something close to the truth but easy to latch on to.

**Comment by davidfarmer** [comment]
Maybe add a sentence after the definition, indicating that there actually are different types of
structures?

**Comment by remkes** [comment]
Good idea. Done.
